config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registration, only: [ :new, :create ]
  resource :settings, only: [ :edit, :update ]
  resources :passwords, param: :token
  get "dashboard/index"
  # resources :budget_line_items
  # resources :expenses
  # resources :categoryfs
  # resources :categories
  # resources :budget_periods
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  #
  resources :expense_templates

  resources :budget_periods do
    resources :budget_line_items
    resources :expenses, only: [ :new, :create ]
    resources :income_events
  end

  resources :income_events do
    resources :planned_expenses do
      member do
        patch :apply
        patch :move
      end
    end
    member do
      get :receive
      patch :receive
      post :apply_all
    end
  end

  resources :categories
  resources :expenses

  resources :shopping_items do
    member do
      patch :mark_as_purchased
      get :convert_to_planned_expense
      post :convert_to_planned_expense
      get :convert_to_expense
      post :convert_to_expense
      get :link_to_planned_expense
      patch :link_to_planned_expense
    end
  end

  resources :inventory_items do
    member do
      post :add_to_shopping_list
      patch :update_stock_state
    end
  end

  resources :accounts do
    resources :account_memberships, except: [ :show ]
  end
  post "account_switches", to: "account_switches#create", as: :account_switch

  get "reports", to: "reports#index", as: :reports
  get "reports/by_date", to: "reports#by_date", as: :reports_by_date
  get "reports/spending_by_category", to: "reports#spending_by_category", as: :reports_spending_by_category
  get "reports/category_trends", to: "reports#category_trends", as: :reports_category_trends

  namespace :task do
    resources :areas, controller: "areas", path: "areas"
    resources :recurring_tasks do
      member do
        patch :mark_done
      end
    end
  end

  namespace :projects do
    resources :projects do
      resources :tasks
      resources :docs
      resources :links
    end
    resources :docs, only: [ :index, :show, :new, :create, :edit, :update, :destroy ], controller: "standalone_docs" do
      resources :doc_links, only: [ :create, :destroy ]
    end
    resources :links, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  end

  root "dashboard#index"
end

app/models/projects/doc.rb
module Projects
  class Doc < ApplicationRecord
    DOC_TYPES = %w[file note].freeze

    belongs_to :account
    has_many :project_docs, dependent: :destroy
    has_many :projects, through: :project_docs
    has_many :doc_links, dependent: :destroy
    has_many :links, through: :doc_links

    before_create :set_account

    validates :title, presence: true, uniqueness: { scope: :account_id }
    validates :doc_type, inclusion: { in: DOC_TYPES }

    scope :for_account, ->(account) { where(account_id: account.id) }

    private

    def set_account
      self.account = Current.account if account.nil?
    end
  end
end

app/models/projects/project_doc.rb
module Projects
  class ProjectDoc < ApplicationRecord
    belongs_to :project
    belongs_to :doc
  end
end

app/controllers/projects/doc_links_controller.rb
module Projects
  class DocLinksController < ApplicationController
    before_action :set_doc
    before_action :set_link, only: [ :destroy ]

    def create
      @link = Projects::Link.for_account(Current.account).find(params[:link_id])

      if @doc.links << @link
        redirect_to doc_path, notice: t("projects.flash.link_added")
      else
        redirect_to doc_path, alert: t("projects.flash.link_add_failed")
      end
    rescue ActiveRecord::RecordInvalid
      redirect_to doc_path, alert: t("projects.flash.link_already_added")
    end

    def destroy
      @doc.links.delete(@link)
      redirect_to doc_path, notice: t("projects.flash.link_removed")
    end

    private

    def set_doc
      @doc = Projects::Doc.for_account(Current.account).find(params[:doc_id])
    end

    def set_link
      @link = @doc.links.find(params[:id])
    end

    def doc_path
      # If doc is associated with a project from params, redirect there
      # Otherwise, redirect to standalone doc view
      if params[:project_id]
        projects_project_doc_path(params[:project_id], @doc)
      elsif @doc.projects.any?
        projects_project_doc_path(@doc.projects.first, @doc)
      else
        projects_doc_path(@doc)
      end
    end
  end
end

app/controllers/projects/docs_controller.rb
module Projects
  class DocsController < ApplicationController
    before_action :set_project
    before_action :set_doc, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_doc_access, only: [ :show, :edit, :update, :destroy ]

    def index
      @docs = @project.docs.order(created_at: :desc)
    end

    def show
    end

    def new
      @doc = Doc.new
    end

    def create
      @doc = Doc.new(doc_params)
      @doc.account = Current.account

      if @doc.save
        @project.docs << @doc unless @project.docs.include?(@doc)
        redirect_to projects_project_doc_path(@project, @doc), notice: t("docs.flash.created")
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @doc.update(doc_params)
        respond_to do |format|
          format.html { redirect_to projects_project_doc_path(@project, @doc), notice: t("docs.flash.updated") }
          format.json { render json: { id: @doc.id }, status: :ok }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @doc.errors.full_messages }, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @doc.destroy
      redirect_to projects_project_docs_path(@project), notice: t("docs.flash.destroyed")
    end

    private

    def set_project
      @project = Project.for_account(Current.account).find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_url
    end

    def set_doc
      @doc = @project.docs.includes(:links).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_project_docs_path(@project)
    end

    def ensure_doc_access
      unless @doc && @doc.account_id == Current.account.id
        redirect_to projects_project_docs_path(@project)
      end
    end

    def doc_params
      params.require(:doc).permit(:title, :content, :doc_type)
    end
  end
end

app/controllers/projects/links_controller.rb
module Projects
  class LinksController < ApplicationController
    before_action :set_project, if: -> { params[:project_id].present? }
    before_action :set_link, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_link_access, only: [ :show, :edit, :update, :destroy ]

    def index
      @links = if @project
        @project.links.order(created_at: :desc)
      else
        Link.for_account(Current.account).order(created_at: :desc)
      end
    end

    def show
    end

    def new
      @link = Link.new
      @return_to_doc_id = params[:return_to_doc_id]
      @return_to_project_id = params[:return_to_project_id]
    end

    def create
      # Extract return_to parameters before creating the link
      return_to_doc_id = params[:link]&.delete(:return_to_doc_id)
      return_to_project_id = params[:link]&.delete(:return_to_project_id)

      @link = Link.new(link_params)
      @link.account = Current.account

      if @link.save
        # Associate with project if provided
        if @project
          @project.links << @link unless @project.links.include?(@link)
        end

        # Associate with doc if return params provided
        if return_to_doc_id.present?
          doc = Doc.for_account(Current.account).find(return_to_doc_id)
          doc.links << @link unless doc.links.include?(@link)
          redirect_to projects_project_doc_path(return_to_project_id, doc), notice: t("links.flash.created")
        elsif @project
          redirect_to projects_project_link_path(@project, @link), notice: t("links.flash.created")
        else
          redirect_to projects_link_path(@link), notice: t("links.flash.created")
        end
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @link.update(link_params)
        respond_to do |format|
          if @project
            format.html { redirect_to projects_project_link_path(@project, @link), notice: t("links.flash.updated") }
          else
            format.html { redirect_to projects_link_path(@link), notice: t("links.flash.updated") }
          end
          format.json { render json: { id: @link.id }, status: :ok }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @link.errors.full_messages }, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @link.destroy
      if @project
        redirect_to projects_project_links_path(@project), notice: t("links.flash.destroyed")
      else
        redirect_to projects_links_path, notice: t("links.flash.destroyed")
      end
    end

    private

    def set_project
      @project = Project.for_account(Current.account).find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_projects_path
    end

    def set_link
      if @project
        @link = @project.links.find(params[:id])
      else
        @link = Link.for_account(Current.account).find(params[:id])
      end
    rescue ActiveRecord::RecordNotFound
      if @project
        redirect_to projects_project_links_path(@project)
      else
        redirect_to projects_links_path
      end
    end

    def ensure_link_access
      unless @link && @link.account_id == Current.account.id
        if @project
          redirect_to projects_project_links_path(@project)
        else
          redirect_to projects_links_path
        end
      end
    end

    def link_params
      params.require(:link).permit(:title, :url, :description, :link_type)
    end
  end
end

app/controllers/projects/projects_controller.rb
module Projects
  class ProjectsController < ApplicationController
    before_action :set_project, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_project_access, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_project_owner, only: [ :edit, :update, :destroy ]

    def index
      @projects = Project.for_account(Current.account).order(created_at: :desc)
    end

    def show
      @tasks = @project.tasks.order(created_at: :desc)
      @docs = @project.docs
      @links = @project.links
      @meetings = @project.meetings.upcoming
    end

    def new
      @project = Project.for_account(Current.account).build
    end

    def create
      @project = Project.for_account(Current.account).build(project_params)
      @project.user = Current.user
      @project.account = Current.account

      if @project.save
        redirect_to @project, notice: t("projects.flash.created")
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @project.update(project_params)
        redirect_to @project, notice: t("projects.flash.updated")
      else
        render :edit
      end
    end

    def destroy
      @project.destroy
      redirect_to projects_projects_url, notice: t("projects.flash.destroyed")
    end

    private

    def set_project
      @project = Project.for_account(Current.account).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_projects_url
    end

    def ensure_project_access
      unless @project && @project.account_id == Current.account.id
        redirect_to projects_projects_url
      end
    end

    def ensure_project_owner
      unless @project.owner_id == Current.user.id
        redirect_to @project
      end
    end

    def project_params
      params.require(:project).permit(:name, :summary, :status, :priority, :start_date, :end_date)
    end
  end
end

app/controllers/projects/standalone_docs_controller.rb
module Projects
  class StandaloneDocsController < ApplicationController
    before_action :set_doc, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_doc_access, only: [ :show, :edit, :update, :destroy ]

    def index
      @docs = Doc.for_account(Current.account).order(created_at: :desc)
    end

    def show
    end

    def new
      @doc = Doc.new
    end

    def create
      @doc = Doc.new(doc_params)
      @doc.account = Current.account

      if @doc.save
        redirect_to projects_doc_path(@doc), notice: t("docs.flash.created")
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @doc.update(doc_params)
        respond_to do |format|
          format.html { redirect_to projects_doc_path(@doc), notice: t("docs.flash.updated") }
          format.json { render json: { id: @doc.id }, status: :ok }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @doc.errors.full_messages }, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @doc.destroy
      redirect_to projects_docs_path, notice: t("docs.flash.destroyed")
    end

    private

    def set_doc
      @doc = Doc.for_account(Current.account).includes(:links, :projects).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_docs_path
    end

    def ensure_doc_access
      unless @doc && @doc.account_id == Current.account.id
        redirect_to projects_docs_path
      end
    end

    def doc_params
      params.require(:doc).permit(:title, :content, :doc_type)
    end
  end
end

app/controllers/projects/tasks_controller.rb
module Projects
  class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, only: [ :show, :edit, :update, :destroy ]
    before_action :ensure_task_access, only: [ :show, :edit, :update, :destroy ]

    def index
      @tasks = @project.tasks.order(created_at: :desc)
    end

    def show
    end

    def new
      @task = @project.tasks.build
    end

    def create
      @task = @project.tasks.build(task_params)
      @task.user = Current.user
      @task.account = Current.account

      if @task.save
        redirect_to projects_project_task_path(@project, @task), notice: t("tasks.flash.created")
      else
        Rails.logger.error("Task validation errors: #{@task.errors.full_messages}")
        render :new
      end
    end

    def edit
    end

    def update
      if @task.update(task_params)
        respond_to do |format|
          format.html { redirect_to projects_project_task_path(@project, @task), notice: t("tasks.flash.updated") }
          format.json { render json: { id: @task.id, status: @task.status }, status: :ok }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @task.errors.full_messages }, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @task.destroy
      redirect_to projects_project_tasks_url(@project), notice: t("tasks.flash.destroyed")
    end

    private

    def set_project
      @project = Project.for_account(Current.account).find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_url
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to project_tasks_url(@project)
    end

    def ensure_task_access
      unless @task && @task.account_id == Current.account.id
        redirect_to project_tasks_url(@project)
      end
    end

    def task_params
      params.require(:task).permit(:title, :description, :status, :priority, :due_date)
    end
  end
end

app/controllers/task/areas_controller.rb
# frozen_string_literal: true

module Task
  class AreasController < ApplicationController
    before_action :set_task_area, only: [ :show, :edit, :update, :destroy ]

    def index
      @task_areas = TaskArea.for_account(Current.account).order(:name)
    end

    def show
    end

    def new
      @task_area = TaskArea.new
    end

    def create
      @task_area = TaskArea.for_account(Current.account).new(task_area_params)
      @task_area.account = Current.account

      if @task_area.save
        redirect_to task_areas_path, notice: t("task.areas.flash.created")
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @task_area.update(task_area_params)
        redirect_to task_areas_path, notice: t("task.areas.flash.updated")
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @task_area.destroy!
      redirect_to task_areas_path, status: :see_other, notice: t("task.areas.flash.destroyed")
    end

    private

    def set_task_area
      @task_area = TaskArea.for_account(Current.account).find(params[:id])
    end

    def task_area_params
      params.require(:task_area).permit(:name)
    end
  end
end

app/views/projects/tasks/edit.html.erb
<div class="container mx-auto px-4 py-8 max-w-2xl">
  <h1 class="text-3xl font-bold text-slate-900 mb-2">Edit Task</h1>
  <p class="text-slate-600 mb-8"><%= @task.task_number %> - for <%= link_to @project.name, projects_project_path(@project), class: "text-blue-600 hover:text-blue-800" %></p>

  <div class="bg-white rounded-lg shadow p-6">
    <%= form_with model: [@project, @task], url: projects_project_task_path(@project, @task), method: :patch, local: true, scope: :task do |form| %>
      <% if @task.errors.any? %>
        <div class="mb-6 bg-red-50 border border-red-200 rounded p-4">
          <h2 class="text-sm font-semibold text-red-800 mb-2"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul class="text-sm text-red-700 list-disc list-inside">
            <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-6">
        <%= form.label :title, "Task Title", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.text_field :title, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>

      <div class="mb-6">
        <%= form.label :description, "Description", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.text_area :description, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500", rows: 5 %>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div>
          <%= form.label :status, "Status", class: "block text-sm font-semibold text-slate-700 mb-2" %>
          <%= form.select :status, Projects::Task::STATUSES.map { |s| [s.humanize, s] }, {}, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
        </div>

        <div>
          <%= form.label :priority, "Priority", class: "block text-sm font-semibold text-slate-700 mb-2" %>
          <%= form.select :priority, Projects::Task::PRIORITIES.map { |p| [p.humanize, p] }, {}, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
        </div>
      </div>

      <div class="mb-6">
        <%= form.label :due_date, "Due Date", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.date_field :due_date, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>

      <div class="flex gap-3">
        <%= form.submit "Update Task", class: "px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium" %>
        <%= link_to "Cancel", projects_project_task_path(@project, @task), class: "px-6 py-2 text-slate-700 border border-slate-300 rounded-lg hover:bg-slate-50 font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/tasks/index.html.erb
<div class="container mx-auto px-4 py-8">
  <div class="mb-8">
    <h1 class="text-3xl font-bold text-slate-900"><%= link_to @project.name, projects_project_path(@project), class: "hover:text-blue-600" %></h1>
    <p class="text-slate-600 mt-2">Tasks</p>
  </div>

  <div class="mb-6">
    <%= render AddButtonComponent.new(label: "New Task", path: new_projects_project_task_path(@project)) %>
  </div>

  <div class="bg-white rounded-lg shadow">
    <% if @tasks.any? %>
      <% @tasks.each do |task| %>
        <%= render Projects::TaskRowComponent.new(task: task, project: @project) %>
      <% end %>
    <% else %>
      <div class="p-8 text-center text-slate-600">
        <%= link_to "Create your first task", new_projects_project_task_path(@project), class: "text-blue-600 hover:text-blue-800 font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/tasks/new.html.erb
<div class="container mx-auto px-4 py-8 max-w-2xl">
  <h1 class="text-3xl font-bold text-slate-900 mb-2">Create New Task</h1>
  <p class="text-slate-600 mb-8">for <%= link_to @project.name, projects_project_path(@project), class: "text-blue-600 hover:text-blue-800" %></p>

  <div class="bg-white rounded-lg shadow p-6">
    <%= form_with model: [@project, @task], url: projects_project_tasks_path(@project), method: :post, local: true, scope: :task do |form| %>
      <% if @task.errors.any? %>
        <div class="mb-6 bg-red-50 border border-red-200 rounded p-4">
          <h2 class="text-sm font-semibold text-red-800 mb-2"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul class="text-sm text-red-700 list-disc list-inside">
            <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-6">
        <%= form.label :title, "Task Title", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.text_field :title, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "e.g., Set up authentication" %>
      </div>

      <div class="mb-6">
        <%= form.label :description, "Description", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.text_area :description, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500", rows: 5, placeholder: "Add details, notes, or instructions (supports markdown)..." %>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div>
          <%= form.label :status, "Status", class: "block text-sm font-semibold text-slate-700 mb-2" %>
          <%= form.select :status, Projects::Task::STATUSES.map { |s| [s.humanize, s] }, {}, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
        </div>

        <div>
          <%= form.label :priority, "Priority", class: "block text-sm font-semibold text-slate-700 mb-2" %>
          <%= form.select :priority, Projects::Task::PRIORITIES.map { |p| [p.humanize, p] }, {}, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
        </div>
      </div>

      <div class="mb-6">
        <%= form.label :due_date, "Due Date", class: "block text-sm font-semibold text-slate-700 mb-2" %>
        <%= form.date_field :due_date, class: "w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>

      <div class="flex gap-3">
        <%= form.submit "Create Task", class: "px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium" %>
        <%= link_to "Cancel", projects_project_tasks_path(@project), class: "px-6 py-2 text-slate-700 border border-slate-300 rounded-lg hover:bg-slate-50 font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/tasks/show.html.erb
<div class="container mx-auto px-4 py-8">
  <div class="mb-8">
    <div class="flex items-center justify-between">
      <div>
        <p class="text-sm font-medium text-slate-600"><%= link_to @project.name, projects_project_path(@project), class: "text-blue-600 hover:text-blue-800" %></p>
        <h1 class="text-3xl font-bold text-slate-900 mt-1"><%= @task.task_number %> - <%= @task.title %></h1>
        <div class="flex items-center gap-3 mt-3">
          <%= render StatusBadgeComponent.new(status: @task.status, type: :status) %>
          <%= render StatusBadgeComponent.new(status: @task.priority, type: :priority) %>
        </div>
      </div>
      <div class="flex gap-2">
        <%= render EditButtonComponent.new(path: edit_projects_project_task_path(@project, @task)) %>
        <%= render DeleteButtonComponent.new(path: projects_project_task_path(@project, @task)) %>
      </div>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
    <div class="bg-white rounded-lg shadow p-6">
      <h3 class="text-sm font-semibold text-slate-600">Owner</h3>
      <p class="text-lg font-bold text-slate-900 mt-2"><%= @task.user.name %></p>
    </div>

    <div class="bg-white rounded-lg shadow p-6">
      <h3 class="text-sm font-semibold text-slate-600">Status</h3>
      <p class="text-lg font-bold text-slate-900 mt-2"><%= @task.status.humanize %></p>
    </div>

    <div class="bg-white rounded-lg shadow p-6">
      <h3 class="text-sm font-semibold text-slate-600">Priority</h3>
      <p class="text-lg font-bold text-slate-900 mt-2"><%= @task.priority.humanize %></p>
    </div>
  </div>

  <% if @task.due_date %>
    <div class="bg-white rounded-lg shadow p-6 mb-8">
      <h3 class="text-sm font-semibold text-slate-600">Due Date</h3>
      <p class="text-lg text-slate-900 mt-2"><%= @task.due_date.strftime("%B %d, %Y") %></p>
      <% if @task.due_date < Date.current && @task.status != "done" %>
        <p class="text-sm text-red-600 font-semibold mt-2">Overdue</p>
      <% end %>
    </div>
  <% end %>

  <% if @task.description.present? %>
    <div class="bg-white rounded-lg shadow p-6 mb-8">
      <h3 class="text-lg font-semibold text-slate-900 mb-3">Description</h3>
      <div class="markdown-content text-slate-700">
        <%= render_markdown(@task.description) %>
      </div>
    </div>
  <% end %>

  <%= link_to "← Back to tasks", projects_project_tasks_path(@project), class: "text-blue-600 hover:text-blue-800 font-medium" %>
</div>